### ISSUE TITLE
Any chance for an update? 

### ISSUE THREAD

**Issue by smooreace** [d6rks1lv3rz3r0/DU-Screen-Flair#8]
An update would be great. These were some of the best inventory screens that there were. Now all are broke. Or if we could get some un-minified work someone else could keep these beauties alive!

**Comment by d6rks1lv3rz3r0** [comment]
None of these are minified lol they are just the way game stores them in that particular JSON structure.

But yes most of these will not work due to updated API calls, and then those that would otherwise work won't be too useful due to HTML on screens not being rendered for most people by default.

There are no plans to revive these screens as they are, as in with the same visual theme. However most of them already are ported to Modern API, you can find them in my GitHub.

Let's see:
HubHub - > ModernHubHub
ContainerSignM -> ModernHubHub
Container Signs S XS and Hub Panel L - > Modern Screen Flair \ Screens has assets, many examples in DU Lua chat for variations.
Simple Sign, Dispenser Sign -> Modern Screen Flair \ Screens 

No Equivalents Yet:
Industry Selector
Store Signs
Welcome Screen
